<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="UXINMIC-5I88O0I" name="com.test.testng.TimeOutTest" tests="2" failures="0" timestamp="2019-09-19T11:39:45 CST" time="4.018" errors="1">
  <testcase name="testFailed" time="2.016" classname="com.test.testng.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.testng.TimeOutTest.testFailed() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.testng.TimeOutTest.testFailed() didn't finish within the time-out 2000
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testFailed -->
  <testcase name="testSuccess" time="2.002" classname="com.test.testng.TimeOutTest"/>
</testsuite> <!-- com.test.testng.TimeOutTest -->
